# AUTO-GENERATED by: python tests/test_architecture_boundary.py --regen
# Shrinks as Phase 1 migration steps land. Never grows.
KNOWN_VIOLATIONS: frozenset = frozenset(
    {
        ("version_stamp.cli.commands", "version_stamp.cli.snapshot"),
        ("version_stamp.cli.entry", "version_stamp.cli.experiment"),
        ("version_stamp.cli.entry", "version_stamp.core.experiment_writer"),
        ("version_stamp.cli.entry", "version_stamp.ui.cli"),
        ("version_stamp.cli.output", "version_stamp.cli.snapshot"),
    }
)
