# old_name -> new_name mappings for core experiment modules (filled by step h2)
TABLE: dict = {
    "version_stamp.core.experiment_env": "vmn_exp.core.env",
    "version_stamp.core.experiment_fold": "vmn_exp.core.fold",
    "version_stamp.core.experiment_from_snapshot": "vmn_exp.core.from_snapshot",
    "version_stamp.core.experiment_index": "vmn_exp.core.index",
    "version_stamp.core.experiment_index_logs": "vmn_exp.core.index_logs",
    "version_stamp.core.experiment_index_record": "vmn_exp.core.index_record",
    "version_stamp.core.experiment_index_snapshot": "vmn_exp.core.index_snapshot",
    "version_stamp.core.experiment_index_store": "vmn_exp.core.index_store",
    "version_stamp.core.experiment_index_sweep": "vmn_exp.core.index_sweep",
    "version_stamp.core.experiment_index_workers": "vmn_exp.core.index_workers",
    "version_stamp.core.experiment_inputs": "vmn_exp.core.inputs",
    "version_stamp.core.experiment_log": "vmn_exp.core.log",
    "version_stamp.core.experiment_logfiles": "vmn_exp.core.logfiles",
    "version_stamp.core.experiment_manage": "vmn_exp.core.manage",
    "version_stamp.core.experiment_provenance": "vmn_exp.core.provenance",
    "version_stamp.core.experiment_query": "vmn_exp.core.query",
    "version_stamp.core.experiment_refs": "vmn_exp.core.refs",
    "version_stamp.core.experiment_reserved": "vmn_exp.core.reserved",
    "version_stamp.core.experiment_status": "vmn_exp.core.status",
    "version_stamp.core.experiment_storage_resolve": "vmn_exp.core.storage_resolve",
    "version_stamp.core.experiment_tree": "vmn_exp.core.tree",
    "version_stamp.core.experiment_values": "vmn_exp.core.values",
    "version_stamp.core.experiment_writer": "vmn_exp.core.writer",
    "version_stamp.core.jsonl_tail": "vmn_exp.core.jsonl_tail",
    "version_stamp.core.background": "vmn_exp.core.background",
    "version_stamp.core.best_effort": "vmn_exp.core.best_effort",
    "version_stamp.core.record_files": "vmn_exp.core.record_files",
}
