# AUTO-GENERATED by: python packages/vmn-exp/tests/test_architecture_boundary.py --regen
# Shrinks as Phase 1 migration steps land. Never grows.
KNOWN_VIOLATIONS: frozenset = frozenset(
    {
    }
)
