#!/usr/bin/env python3
"""Interactive configuration TUI for vmn."""
import copy
import os
import pathlib
import subprocess
import sys

import questionary
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from version_stamp.backends.git import GitBackend
from version_stamp.core.logging import VMN_LOGGER, measure_runtime_decorator
from version_stamp.core.models import AppConf, VMN_DEFAULT_CONF
from version_stamp.core.utils import branch_to_conf_prefix
from version_stamp.cli.constants import (
    INIT_FILENAME,
    _CONFIG_DESCRIPTIONS,
    _ROOT_CONFIG_DESCRIPTIONS,
)
from version_stamp.stamping.base import IVersionsStamper


@measure_runtime_decorator
def _read_raw_conf(conf_path):
    if not os.path.isfile(conf_path):
        return {}
    with open(conf_path, "r") as f:
        data = yaml.safe_load(f)
    if data and "conf" in data:
        return data["conf"]
    return {}


def _write_full_config(conf_path, raw_conf):
    pathlib.Path(os.path.dirname(conf_path)).mkdir(parents=True, exist_ok=True)
    ver_conf_yml = {"conf": raw_conf}
    with open(conf_path, "w+") as f:
        f.write("# Autogenerated by vmn. You can edit this configuration file\n")
        yaml.dump(ver_conf_yml, f, sort_keys=True)


@measure_runtime_decorator
def handle_config(vmn_ctx):
    vmn_root_path = vmn_ctx.vcs.vmn_root_path

    # --global mode: edit repo-level .vmn/conf.yml
    if vmn_ctx.args.global_conf:
        conf_path = os.path.join(vmn_root_path, ".vmn", INIT_FILENAME)
        if vmn_ctx.args.vim:
            return _config_vim(conf_path)
        return _config_interactive(conf_path, _CONFIG_DESCRIPTIONS, vmn_root_path)

    # No app name: list managed apps
    if vmn_ctx.vcs.name is None:
        return _config_list_apps(vmn_root_path)

    # --branch mode: edit branch-specific config
    if vmn_ctx.args.branch:
        prefix = branch_to_conf_prefix(vmn_ctx.vcs.backend.active_branch)
        if vmn_ctx.args.root:
            if vmn_ctx.vcs.root_app_conf_path is None:
                VMN_LOGGER.error(
                    f"'{vmn_ctx.vcs.name}' is not a root app (name must contain '/')."
                )
                return 1
            conf_path = os.path.join(
                vmn_ctx.vcs.root_app_dir_path,
                f"{prefix}_root_conf.yml",
            )
            descriptions = _ROOT_CONFIG_DESCRIPTIONS
        else:
            conf_path = os.path.join(
                vmn_ctx.vcs.app_dir_path,
                f"{prefix}_conf.yml",
            )
            descriptions = _CONFIG_DESCRIPTIONS
        if vmn_ctx.args.vim:
            return _config_vim(conf_path, create_if_missing=True)
        return _config_interactive(conf_path, descriptions, vmn_root_path)

    # --vim mode
    if vmn_ctx.args.vim:
        if vmn_ctx.args.root:
            if vmn_ctx.vcs.root_app_conf_path is None:
                VMN_LOGGER.error(
                    f"'{vmn_ctx.vcs.name}' is not a root app (name must contain '/')."
                )
                return 1
            return _config_vim(vmn_ctx.vcs.root_app_conf_path)
        return _config_vim(vmn_ctx.vcs.app_conf_path)

    # --root mode: edit root_conf.yml
    if vmn_ctx.args.root:
        if vmn_ctx.vcs.root_app_conf_path is None:
            VMN_LOGGER.error(
                f"'{vmn_ctx.vcs.name}' is not a root app (name must contain '/')."
            )
            return 1
        return _config_interactive(
            vmn_ctx.vcs.root_app_conf_path, _ROOT_CONFIG_DESCRIPTIONS, vmn_root_path
        )

    # Default: interactive TUI for per-app conf.yml
    if not vmn_ctx.vcs.conf_file_exists:
        VMN_LOGGER.error(
            f"No config file found for '{vmn_ctx.vcs.name}'. "
            f"Run 'vmn init-app {vmn_ctx.vcs.name}' first."
        )
        return 1

    return _config_interactive(
        vmn_ctx.vcs.app_conf_path, _CONFIG_DESCRIPTIONS, vmn_root_path
    )


def _config_list_apps(vmn_root_path):
    vmn_dir = os.path.join(vmn_root_path, ".vmn")
    if not os.path.isdir(vmn_dir):
        VMN_LOGGER.error(
            "vmn is not initialized in this repository. Run 'vmn init' first."
        )
        return 1

    apps = []
    for dirpath, dirnames, filenames in os.walk(vmn_dir):
        has_conf = any(
            f == "conf.yml" or f.endswith("_conf.yml")
            for f in filenames
            if f != "root_conf.yml" and not f.endswith("_root_conf.yml")
        )
        if has_conf:
            rel = os.path.relpath(dirpath, vmn_dir)
            if rel != ".":
                apps.append(rel.replace(os.sep, "/"))

    if not apps:
        print("No managed apps found. Use 'vmn init-app <name>' to initialize an app.")
        return 0

    console = Console()
    table = Table(show_header=False, box=None, padding=(0, 2))
    for app in sorted(apps):
        table.add_row(Text(app, style="cyan"))
    console.print(Panel(table, title="Managed apps", border_style="blue"))
    return 0


_rich_console = Console()


def _render_config_panel(raw_conf, descriptions, modified, conf_path):
    table = Table(show_header=True, header_style="bold", box=None, padding=(0, 2))
    table.add_column("Setting", style="cyan", no_wrap=True)
    table.add_column("Value", style="white")
    table.add_column("Description", style="dim", max_width=44)

    for key in descriptions:
        meta = descriptions[key]
        current = raw_conf.get(key, VMN_DEFAULT_CONF.get(key))
        short = _format_value_short(current)

        if isinstance(current, bool):
            val_style = "green" if current else "red"
        elif isinstance(current, dict) and not current:
            val_style = "dim"
        else:
            val_style = "yellow"

        table.add_row(key, Text(short, style=val_style), meta["description"])

    title = os.path.relpath(conf_path)
    if modified:
        title += " [bold red]*[/bold red]"
    _rich_console.print()
    _rich_console.print(Panel(table, title=title, border_style="blue"))


def _config_interactive(conf_path, descriptions, vmn_root_path):
    if not sys.stdin.isatty():
        VMN_LOGGER.error(
            "Interactive config requires a terminal. Use --vim instead."
        )
        return 1

    raw_conf = _read_raw_conf(conf_path)
    modified = False
    keys = list(descriptions.keys())

    while True:
        _render_config_panel(raw_conf, descriptions, modified, conf_path)

        choices = []
        for key in keys:
            meta = descriptions[key]
            current = raw_conf.get(key, VMN_DEFAULT_CONF.get(key))
            short = _format_value_short(current)
            pad = "." * max(1, 40 - len(key) - len(short))
            choices.append(
                questionary.Choice(
                    title=f"  {key} {pad} {short}",
                    value=key,
                )
            )
        choices.append(questionary.Choice(title="  Save & quit", value="_save"))
        choices.append(questionary.Choice(title="  Quit without saving", value="_quit"))

        choice = questionary.select(
            "Select a setting to edit",
            choices=choices,
            use_shortcuts=False,
        ).ask()

        if choice is None or choice == "_quit":
            if modified:
                confirm = questionary.confirm(
                    "Discard unsaved changes?", default=False
                ).ask()
                if not confirm:
                    continue
            return 0

        if choice == "_save":
            _write_full_config(conf_path, raw_conf)
            _rich_console.print(
                f"\n  [green]Configuration saved to[/green] [bold]{conf_path}[/bold]"
            )
            return 0

        new_val = _edit_key(choice, raw_conf, descriptions, vmn_root_path)
        if new_val is not _SENTINEL:
            raw_conf[choice] = new_val
            modified = True


_SENTINEL = object()


def _edit_key(key, raw_conf, descriptions, vmn_root_path):
    meta = descriptions[key]
    current = raw_conf.get(key, VMN_DEFAULT_CONF.get(key))
    config_type = meta["type"]

    _rich_console.print(f"\n  [dim]{meta['description']}[/dim]")

    if config_type == "bool":
        return _edit_bool(key, current)
    elif config_type == "string":
        return _edit_string(key, current, meta)
    elif config_type == "choice":
        return _edit_choice(key, current, meta)
    elif config_type == "bool_or_dict":
        return _edit_bool_or_dict(key, current)
    elif config_type == "nested_dict":
        return _edit_nested_dict(key, current, meta, vmn_root_path)
    return _SENTINEL


def _edit_bool(key, current):
    default = current if isinstance(current, bool) else False
    result = questionary.confirm(f"  {key}", default=default).ask()
    if result is None:
        return _SENTINEL
    return result


def _edit_string(key, current, meta):
    default = current if isinstance(current, str) else ""
    if key == "template":
        print(
            "  Placeholders: {major}, {minor}, {patch}, {hotfix}, "
            "{prerelease}, {rcn}, {buildmetadata}"
        )
        print("  Wrap in [] for optional sections.")
        if "example" in meta:
            print(f"  Example: {meta['example']}")

    def validate_template(val):
        if key != "template":
            return True
        try:
            IVersionsStamper.parse_template(val)
            return True
        except Exception:
            return "Invalid template format."

    result = questionary.text(
        f"  {key}",
        default=default,
        validate=validate_template,
    ).ask()
    if result is None:
        return _SENTINEL
    return result


def _edit_choice(key, current, meta):
    choices = meta["choices"]
    default = current if current in choices else choices[0]
    result = questionary.select(
        f"  {key}",
        choices=choices,
        default=default,
    ).ask()
    if result is None:
        return _SENTINEL
    return result


def _edit_bool_or_dict(key, current):
    is_enabled = bool(current) if not isinstance(current, dict) else bool(current)
    result = questionary.confirm(f"  Enable {key}?", default=is_enabled).ask()
    if result is None:
        return _SENTINEL
    return True if result else {}


_NESTED_EDITORS = {
    "version_backends": lambda cur, root: _edit_version_backends(cur, root),
    "deps": lambda cur, root: _edit_deps(cur, root),
    "policies": lambda cur, _root: _edit_policies(cur),
    "external_services": lambda cur, _root: _edit_external_services(cur),
}


def _edit_nested_dict(key, current, meta, vmn_root_path):
    if current is None:
        current = {}
    current = copy.deepcopy(current)
    editor_name = meta.get("ui_editor", meta.get("nested_key", key))

    editor = _NESTED_EDITORS.get(editor_name)
    if editor:
        return editor(current, vmn_root_path)

    return _edit_generic_dict(key, current)


def _edit_version_backends(current, vmn_root_path):
    known_structured = ["npm", "cargo", "poetry", "pep621"]
    known_generic = ["generic_jinja", "generic_selectors"]

    while True:
        choices = []
        if current:
            for name in current:
                choices.append(questionary.Choice(
                    title=f"  {name}: {_format_value_short(current[name])}",
                    value=f"view:{name}",
                ))
        else:
            choices.append(questionary.Choice(
                title="  (no backends configured)", value="_noop", disabled="empty"
            ))

        choices.append(questionary.Choice(title="  + Add backend", value="_add"))
        if current:
            choices.append(questionary.Choice(title="  - Remove backend", value="_remove"))
        choices.append(questionary.Choice(title="  Back", value="_back"))

        action = questionary.select("  version_backends", choices=choices).ask()

        if action is None or action == "_back":
            return current

        if action == "_add":
            all_types = known_structured + known_generic
            be_type = questionary.select(
                "  Backend type", choices=all_types
            ).ask()
            if be_type is None:
                continue

            if be_type in known_structured:
                path = questionary.text(
                    f"  Path to file (relative to repo root)"
                ).ask()
                if path is None:
                    continue
                full = os.path.join(vmn_root_path, path)
                if not os.path.isfile(full):
                    print(f"  Warning: file not found at {full}")
                    proceed = questionary.confirm("  Add anyway?", default=False).ask()
                    if not proceed:
                        continue
                current[be_type] = {"path": path}

            elif be_type == "generic_jinja":
                inp = questionary.text("  Input template file path").ask()
                if inp is None:
                    continue
                out = questionary.text("  Output file path").ask()
                if out is None:
                    continue
                full_inp = os.path.join(vmn_root_path, inp)
                if not os.path.isfile(full_inp):
                    print(f"  Warning: input file not found at {full_inp}")
                entry = {"input_file_path": inp, "output_file_path": out}
                custom = questionary.text(
                    "  Custom keys YAML path (Enter to skip)"
                ).ask()
                if custom:
                    entry["custom_keys_path"] = custom
                existing = current.get("generic_jinja", [])
                existing.append(entry)
                current["generic_jinja"] = existing

            elif be_type == "generic_selectors":
                inp = questionary.text("  Input file path").ask()
                if inp is None:
                    continue
                out = questionary.text(
                    "  Output file path", default=inp
                ).ask()
                if out is None:
                    continue
                full_inp = os.path.join(vmn_root_path, inp)
                if not os.path.isfile(full_inp):
                    print(f"  Warning: input file not found at {full_inp}")
                regex_sel = questionary.text("  Regex selector pattern").ask()
                if regex_sel is None:
                    continue
                regex_sub = questionary.text("  Regex substitution (use {{version}})").ask()
                if regex_sub is None:
                    continue
                entry = {
                    "paths_section": [
                        {"input_file_path": inp, "output_file_path": out}
                    ],
                    "selectors_section": [
                        {"regex_selector": regex_sel, "regex_sub": regex_sub}
                    ],
                }
                existing = current.get("generic_selectors", [])
                existing.append(entry)
                current["generic_selectors"] = existing

        elif action == "_remove":
            names = list(current.keys())
            to_remove = questionary.select("  Remove which backend?", choices=names).ask()
            if to_remove:
                del current[to_remove]

    return current


_PIN_FIELDS = ("branch", "tag", "hash")


def _set_dep_pin(dep_conf, kind, value):
    for f in _PIN_FIELDS:
        dep_conf.pop(f, None)
    if kind and value:
        dep_conf[kind] = value


def _get_dep_branch(full_path):
    try:
        import git
        client = git.Repo(full_path, search_parent_directories=True)
        if not client.head.is_detached:
            branch = client.active_branch.name
        else:
            branch = None
        client.close()
        return branch
    except (git.InvalidGitRepositoryError, git.GitCommandNotFound, OSError):
        return None


def _edit_deps(current, vmn_root_path):
    while True:
        choices = []
        if current:
            for path, dep_conf in current.items():
                vcs = dep_conf.get("vcs_type", "git") if isinstance(dep_conf, dict) else "git"
                pinned = dep_conf.get("branch") or dep_conf.get("tag") or dep_conf.get("hash")
                pin_info = f", pinned: {pinned}" if pinned else ""
                choices.append(questionary.Choice(
                    title=f"  {path} ({vcs}{pin_info})",
                    value=f"view:{path}",
                ))
        else:
            choices.append(questionary.Choice(
                title="  (no dependencies configured)", value="_noop", disabled="empty"
            ))

        choices.append(questionary.Choice(title="  + Add dependency", value="_add"))
        if current:
            choices.append(questionary.Choice(title="  - Remove dependency", value="_remove"))
        choices.append(questionary.Choice(title="  Back", value="_back"))

        action = questionary.select("  deps", choices=choices).ask()

        if action is None or action == "_back":
            return current

        if action.startswith("view:"):
            dep_path = action[5:]
            dep_conf = current[dep_path]
            full_path = os.path.join(vmn_root_path, dep_path)

            print(f"\n  Path: {dep_path}")
            print(f"  VCS:  {dep_conf.get('vcs_type', 'git')}")
            for field in _PIN_FIELDS:
                if field in dep_conf:
                    print(f"  Pinned {field}: {dep_conf[field]}")

            detected_branch = _get_dep_branch(full_path)
            if detected_branch:
                print(f"  Current branch on disk: {detected_branch}")

            pin = questionary.select(
                "  Update pin?",
                choices=["keep current", "branch", "tag", "hash", "remove pin"],
                default="keep current",
            ).ask()
            if pin == "branch":
                val = questionary.text("  Branch name", default=detected_branch or "").ask()
                _set_dep_pin(dep_conf, "branch", val)
            elif pin == "tag":
                val = questionary.text("  Tag name").ask()
                _set_dep_pin(dep_conf, "tag", val)
            elif pin == "hash":
                val = questionary.text("  Commit hash").ask()
                _set_dep_pin(dep_conf, "hash", val)
            elif pin == "remove pin":
                _set_dep_pin(dep_conf, None, None)
            continue

        if action == "_add":
            rel_path = questionary.text(
                "  Relative path to dependency repo (e.g. ../other_repo)"
            ).ask()
            if rel_path is None:
                continue

            full_path = os.path.join(vmn_root_path, rel_path)
            dep_conf = {"vcs_type": "git"}

            if os.path.isdir(full_path):
                details = GitBackend.get_repo_details(full_path)
                if details is not None:
                    _hash, remote, vcs_type = details
                    print(f"  Detected: remote={remote}, vcs_type={vcs_type}")
                    dep_conf["vcs_type"] = vcs_type
                else:
                    print(f"  Warning: {full_path} exists but is not a git repo")
            else:
                print(f"  Warning: directory not found at {full_path}")
                proceed = questionary.confirm("  Add anyway?", default=False).ask()
                if not proceed:
                    continue

            detected_branch = _get_dep_branch(full_path)
            if detected_branch:
                print(f"  Current branch: {detected_branch}")

            pin = questionary.select(
                "  Pin to specific ref?",
                choices=["none", "branch", "tag", "hash"],
                default="branch" if detected_branch else "none",
            ).ask()
            if pin == "branch":
                val = questionary.text("  Branch name", default=detected_branch or "").ask()
                _set_dep_pin(dep_conf, "branch", val)
            elif pin == "tag":
                val = questionary.text("  Tag name").ask()
                _set_dep_pin(dep_conf, "tag", val)
            elif pin == "hash":
                val = questionary.text("  Commit hash").ask()
                _set_dep_pin(dep_conf, "hash", val)

            current[rel_path] = dep_conf

        elif action == "_remove":
            paths = list(current.keys())
            to_remove = questionary.select("  Remove which dep?", choices=paths).ask()
            if to_remove:
                del current[to_remove]

    return current


def _edit_policies(current):
    while True:
        branches = current.get("whitelist_release_branches", [])
        branch_str = ", ".join(branches) if branches else "(none)"

        choices = [
            questionary.Choice(
                title=f"  whitelist_release_branches: {branch_str}",
                value="_edit_branches",
            ),
            questionary.Choice(title="  Clear all policies", value="_clear"),
            questionary.Choice(title="  Back", value="_back"),
        ]

        action = questionary.select("  policies", choices=choices).ask()

        if action is None or action == "_back":
            return current
        elif action == "_clear":
            current.clear()
        elif action == "_edit_branches":
            default = ", ".join(branches)
            val = questionary.text(
                "  Branch names (comma-separated, empty to clear)",
                default=default,
            ).ask()
            if val is None:
                continue
            val = val.strip()
            if val:
                current["whitelist_release_branches"] = [
                    b.strip() for b in val.split(",") if b.strip()
                ]
            else:
                current.pop("whitelist_release_branches", None)

    return current


def _edit_external_services(current):
    while True:
        choices = []
        if current:
            for name, conf in current.items():
                choices.append(questionary.Choice(
                    title=f"  {name}: {_format_value_short(conf)}",
                    value=f"view:{name}",
                ))
        else:
            choices.append(questionary.Choice(
                title="  (no external services configured)",
                value="_noop",
                disabled="empty",
            ))

        choices.append(questionary.Choice(title="  + Add service", value="_add"))
        if current:
            choices.append(questionary.Choice(title="  - Remove service", value="_remove"))
        choices.append(questionary.Choice(title="  Back", value="_back"))

        action = questionary.select("  external_services", choices=choices).ask()

        if action is None or action == "_back":
            return current
        elif action == "_add":
            name = questionary.text("  Service name").ask()
            if name is None:
                continue
            current[name] = {}
        elif action == "_remove":
            names = list(current.keys())
            to_remove = questionary.select("  Remove which?", choices=names).ask()
            if to_remove:
                del current[to_remove]

    return current


def _edit_generic_dict(key, current):
    print(f"  Current value: {yaml.dump(current, default_flow_style=False).strip()}")
    val = questionary.text(
        f"  Enter YAML value (or Enter to keep current)",
    ).ask()
    if val is None or val.strip() == "":
        return _SENTINEL
    try:
        parsed = yaml.safe_load(val)
        if isinstance(parsed, dict):
            return parsed
        print("  Expected a dict value.")
    except Exception:
        print("  Invalid YAML.")
    return _SENTINEL


def _config_vim(conf_path, create_if_missing=False):
    editor = os.environ.get("EDITOR", "vim")
    if not os.path.isfile(conf_path):
        if not create_if_missing:
            VMN_LOGGER.error(f"Config file not found: {conf_path}")
            return 1
        _write_full_config(conf_path, {})
        VMN_LOGGER.info(f"Created new config file: {conf_path}")
    return subprocess.call([editor, conf_path])


def _format_value_short(val):
    if isinstance(val, bool):
        return str(val).lower()
    if isinstance(val, dict):
        if not val:
            return "(not set)"
        return f"({len(val)} entries)"
    if isinstance(val, list):
        if not val:
            return "(not set)"
        return f"[{len(val)} items]"
    s = str(val)
    if len(s) > 50:
        return s[:47] + "..."
    return s

