name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -r tests/requirements.txt
          python -m pip install -r tests/test_requirements_docker.txt
          python -m pip install -e .
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"
          git config --global init.defaultBranch master

      - name: Run tests
        run: tests/run_pytest.sh --color --base_log_dir "${RUNNER_TEMP}"
